spec:
  template:
    spec:
      containers:
        - env:
            - name: "MONGO_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: "username"
                  name: "demo-secret"
                  optional: false
            - name: "MONGO_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "password"
                  name: "demo-secret"
                  optional: false
      serviceAccount: springboot-serviceaccount
